AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  ShoppingCartEventDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-shopping-cart-events-table
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      AttributeDefinitions:
        - AttributeName: shoppingCartId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: shoppingCartId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: True

  ShoppingCartEventTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-shopping-cart-events.fifo
      FifoTopic: true

  ShoppingCartLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-shopping-cart-lambda-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-shopping-cart-lambda-cloud-watch-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:eu-west-3:909133997228:*
        - PolicyName: !Sub '${AWS::StackName}-shopping-cart-lambda-dynamo-stream-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource:
                  - !GetAtt ShoppingCartEventDynamoTable.StreamArn
        - PolicyName: !Sub '${AWS::StackName}-shopping-cart-lambda-sns-publish-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - !Ref ShoppingCartEventTopic

  ShoppingCartLambdaStreamToSns:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-shopping-cart-lambda-stream-to-sns'
      Role: !GetAtt ShoppingCartLambdaExecutionRole.Arn
      CodeUri: ./dist/shopping-cart-lambda-stream-to-sns
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30 # default is 3s
      MemorySize: 2048 # default is 128Mi
      Architectures:
        - x86_64
      Environment:
        Variables:
          AWS_SNS_TOPIC_ARN: !Ref ShoppingCartEventTopic
#    Metadata:
#      BuildMethod: esbuild
#      BuildProperties:
#        Minify: false
#        Target: 'es2020'
#        Sourcemap: true
#        EntryPoints:
#          - index.js

  ShoppingCartStreamToLambda:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      FunctionName: !Ref ShoppingCartLambdaStreamToSns
      EventSourceArn: !GetAtt ShoppingCartEventDynamoTable.StreamArn
      StartingPosition: TRIM_HORIZON

  ShoppingCartFakeListenerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-shopping-cart-fake-listener.fifo'
      FifoQueue: true
      DeduplicationScope: messageGroup
      FifoThroughputLimit: perMessageGroupId
      VisibilityTimeout: 650

  ShoppingCartSnsToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: ShoppingCartFakeListenerQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'sns.amazonaws.com'
            Resource:
              - !GetAtt ShoppingCartFakeListenerQueue.Arn
            Action: 'sqs:SendMessage'
            Condition:
              ForAnyValue:ArnEquals:
                'aws:SourceArn':
                  - !Ref ShoppingCartEventTopic

  ShoppingCartFakeListenerSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref ShoppingCartEventTopic
      Endpoint: !GetAtt ShoppingCartFakeListenerQueue.Arn
      RawMessageDelivery: true

Outputs:
  ShoppingCartEventsTableName:
    Value: !Ref ShoppingCartEventDynamoTable
  ShoppingCartEventsStreamArn:
    Value: !GetAtt ShoppingCartEventDynamoTable.StreamArn
  ShoppingCartEventsTopicArn:
    Value: !Ref ShoppingCartEventTopic
  ShoppingCartEventsLambdaName:
    Value: !Ref ShoppingCartLambdaStreamToSns
